name: pure_live_chat
description: Realtime chatting system with audio and video streaming.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



  #UI/UX
  flutter_spinkit: ^4.1.2+1
  loading_overlay: ^0.2.1
  flutter_dotenv: ^2.1.0
  awesome_dialog: ^1.3.0
  flutter_rating_bar: ^3.2.0+1

  #GetX
  get: ^3.24.0
  get_storage: ^1.4.0

  #date
  intl: any

  #network
  connectivity: ^0.4.4
  app_settings: ^4.0.4
  permission_handler: ^5.0.1+1
  flutter_local_notifications: ^3.0.2
  graphql_flutter: ^3.1.0
  cached_network_image: ^2.4.1

  #Firebase
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  firebase_storage: ^7.0.0
  cloud_firestore: ^0.16.0

  #ui insurance
  logger: ^0.9.4
  rename: ^1.2.0

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/bg.png"
    ##--> REPLACE THE app-icon.png FILE IN ASSET/IMAGE AND THEN <--##
    ##--> RUN BELOW CODE TO CHANGE THE APP ICON <--##
    #flutter pub get
    #flutter pub run flutter_launcher_icons:main


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: PottaOne-Regular
      fonts:
        - asset: assets/fonts/PottaOne-Regular.ttf
    - family: PermanentMarker-Regular
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf